#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DOANCOSO")]
	public partial class DBL_DACSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertACCOUNT(ACCOUNT instance);
    partial void UpdateACCOUNT(ACCOUNT instance);
    partial void DeleteACCOUNT(ACCOUNT instance);
    partial void InsertTIEUCHI_SV5T(TIEUCHI_SV5T instance);
    partial void UpdateTIEUCHI_SV5T(TIEUCHI_SV5T instance);
    partial void DeleteTIEUCHI_SV5T(TIEUCHI_SV5T instance);
    partial void InsertCAP_SV5T(CAP_SV5T instance);
    partial void UpdateCAP_SV5T(CAP_SV5T instance);
    partial void DeleteCAP_SV5T(CAP_SV5T instance);
    partial void InsertCHITIET_TC(CHITIET_TC instance);
    partial void UpdateCHITIET_TC(CHITIET_TC instance);
    partial void DeleteCHITIET_TC(CHITIET_TC instance);
    partial void InsertKHOA(KHOA instance);
    partial void UpdateKHOA(KHOA instance);
    partial void DeleteKHOA(KHOA instance);
    partial void InsertKQDANHGIA_ACCOUNT(KQDANHGIA_ACCOUNT instance);
    partial void UpdateKQDANHGIA_ACCOUNT(KQDANHGIA_ACCOUNT instance);
    partial void DeleteKQDANHGIA_ACCOUNT(KQDANHGIA_ACCOUNT instance);
    partial void InsertLHTT(LHTT instance);
    partial void UpdateLHTT(LHTT instance);
    partial void DeleteLHTT(LHTT instance);
    partial void InsertLOP(LOP instance);
    partial void UpdateLOP(LOP instance);
    partial void DeleteLOP(LOP instance);
    partial void InsertNGUOIDANHGIA(NGUOIDANHGIA instance);
    partial void UpdateNGUOIDANHGIA(NGUOIDANHGIA instance);
    partial void DeleteNGUOIDANHGIA(NGUOIDANHGIA instance);
    partial void InsertPHIEUDK_SV5T(PHIEUDK_SV5T instance);
    partial void UpdatePHIEUDK_SV5T(PHIEUDK_SV5T instance);
    partial void DeletePHIEUDK_SV5T(PHIEUDK_SV5T instance);
    #endregion
		
		public DBL_DACSDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DOANCOSOConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBL_DACSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBL_DACSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBL_DACSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBL_DACSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this.GetTable<ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<TIEUCHI_SV5T> TIEUCHI_SV5Ts
		{
			get
			{
				return this.GetTable<TIEUCHI_SV5T>();
			}
		}
		
		public System.Data.Linq.Table<CAP_SV5T> CAP_SV5Ts
		{
			get
			{
				return this.GetTable<CAP_SV5T>();
			}
		}
		
		public System.Data.Linq.Table<CHITIET_TC> CHITIET_TCs
		{
			get
			{
				return this.GetTable<CHITIET_TC>();
			}
		}
		
		public System.Data.Linq.Table<KHOA> KHOAs
		{
			get
			{
				return this.GetTable<KHOA>();
			}
		}
		
		public System.Data.Linq.Table<KQDANHGIA_ACCOUNT> KQDANHGIA_ACCOUNTs
		{
			get
			{
				return this.GetTable<KQDANHGIA_ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<LHTT> LHTTs
		{
			get
			{
				return this.GetTable<LHTT>();
			}
		}
		
		public System.Data.Linq.Table<LOP> LOPs
		{
			get
			{
				return this.GetTable<LOP>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDANHGIA> NGUOIDANHGIAs
		{
			get
			{
				return this.GetTable<NGUOIDANHGIA>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUDK_SV5T> PHIEUDK_SV5Ts
		{
			get
			{
				return this.GetTable<PHIEUDK_SV5T>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACCOUNT")]
	public partial class ACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USERNAME;
		
		private string _MAKHOA;
		
		private string _PASSWORD;
		
		private string _MALOAI;
		
		private bool _QUYEN;
		
		private EntitySet<KQDANHGIA_ACCOUNT> _KQDANHGIA_ACCOUNTs;
		
		private EntitySet<PHIEUDK_SV5T> _PHIEUDK_SV5Ts;
		
		private EntityRef<KHOA> _KHOA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnMAKHOAChanging(string value);
    partial void OnMAKHOAChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnMALOAIChanging(string value);
    partial void OnMALOAIChanged();
    partial void OnQUYENChanging(bool value);
    partial void OnQUYENChanged();
    #endregion
		
		public ACCOUNT()
		{
			this._KQDANHGIA_ACCOUNTs = new EntitySet<KQDANHGIA_ACCOUNT>(new Action<KQDANHGIA_ACCOUNT>(this.attach_KQDANHGIA_ACCOUNTs), new Action<KQDANHGIA_ACCOUNT>(this.detach_KQDANHGIA_ACCOUNTs));
			this._PHIEUDK_SV5Ts = new EntitySet<PHIEUDK_SV5T>(new Action<PHIEUDK_SV5T>(this.attach_PHIEUDK_SV5Ts), new Action<PHIEUDK_SV5T>(this.detach_PHIEUDK_SV5Ts));
			this._KHOA = default(EntityRef<KHOA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHOA", DbType="VarChar(10)")]
		public string MAKHOA
		{
			get
			{
				return this._MAKHOA;
			}
			set
			{
				if ((this._MAKHOA != value))
				{
					if (this._KHOA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHOAChanging(value);
					this.SendPropertyChanging();
					this._MAKHOA = value;
					this.SendPropertyChanged("MAKHOA");
					this.OnMAKHOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="Char(20)")]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYEN", DbType="Bit NOT NULL")]
		public bool QUYEN
		{
			get
			{
				return this._QUYEN;
			}
			set
			{
				if ((this._QUYEN != value))
				{
					this.OnQUYENChanging(value);
					this.SendPropertyChanging();
					this._QUYEN = value;
					this.SendPropertyChanged("QUYEN");
					this.OnQUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_KQDANHGIA_ACCOUNT", Storage="_KQDANHGIA_ACCOUNTs", ThisKey="USERNAME", OtherKey="USERNAME")]
		public EntitySet<KQDANHGIA_ACCOUNT> KQDANHGIA_ACCOUNTs
		{
			get
			{
				return this._KQDANHGIA_ACCOUNTs;
			}
			set
			{
				this._KQDANHGIA_ACCOUNTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_PHIEUDK_SV5T", Storage="_PHIEUDK_SV5Ts", ThisKey="USERNAME", OtherKey="USERNAME")]
		public EntitySet<PHIEUDK_SV5T> PHIEUDK_SV5Ts
		{
			get
			{
				return this._PHIEUDK_SV5Ts;
			}
			set
			{
				this._PHIEUDK_SV5Ts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOA_ACCOUNT", Storage="_KHOA", ThisKey="MAKHOA", OtherKey="MAKHOA", IsForeignKey=true)]
		public KHOA KHOA
		{
			get
			{
				return this._KHOA.Entity;
			}
			set
			{
				KHOA previousValue = this._KHOA.Entity;
				if (((previousValue != value) 
							|| (this._KHOA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOA.Entity = null;
						previousValue.ACCOUNTs.Remove(this);
					}
					this._KHOA.Entity = value;
					if ((value != null))
					{
						value.ACCOUNTs.Add(this);
						this._MAKHOA = value.MAKHOA;
					}
					else
					{
						this._MAKHOA = default(string);
					}
					this.SendPropertyChanged("KHOA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KQDANHGIA_ACCOUNTs(KQDANHGIA_ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = this;
		}
		
		private void detach_KQDANHGIA_ACCOUNTs(KQDANHGIA_ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = null;
		}
		
		private void attach_PHIEUDK_SV5Ts(PHIEUDK_SV5T entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = this;
		}
		
		private void detach_PHIEUDK_SV5Ts(PHIEUDK_SV5T entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIEUCHI_SV5T")]
	public partial class TIEUCHI_SV5T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATC;
		
		private string _TENTC;
		
		private System.Nullable<int> _SOLUONG;
		
		private EntitySet<CHITIET_TC> _CHITIET_TCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATCChanging(string value);
    partial void OnMATCChanged();
    partial void OnTENTCChanging(string value);
    partial void OnTENTCChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public TIEUCHI_SV5T()
		{
			this._CHITIET_TCs = new EntitySet<CHITIET_TC>(new Action<CHITIET_TC>(this.attach_CHITIET_TCs), new Action<CHITIET_TC>(this.detach_CHITIET_TCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATC", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATC
		{
			get
			{
				return this._MATC;
			}
			set
			{
				if ((this._MATC != value))
				{
					this.OnMATCChanging(value);
					this.SendPropertyChanging();
					this._MATC = value;
					this.SendPropertyChanged("MATC");
					this.OnMATCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTC", DbType="NVarChar(200)")]
		public string TENTC
		{
			get
			{
				return this._TENTC;
			}
			set
			{
				if ((this._TENTC != value))
				{
					this.OnTENTCChanging(value);
					this.SendPropertyChanging();
					this._TENTC = value;
					this.SendPropertyChanged("TENTC");
					this.OnTENTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIEUCHI_SV5T_CHITIET_TC", Storage="_CHITIET_TCs", ThisKey="MATC", OtherKey="MATC")]
		public EntitySet<CHITIET_TC> CHITIET_TCs
		{
			get
			{
				return this._CHITIET_TCs;
			}
			set
			{
				this._CHITIET_TCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIET_TCs(CHITIET_TC entity)
		{
			this.SendPropertyChanging();
			entity.TIEUCHI_SV5T = this;
		}
		
		private void detach_CHITIET_TCs(CHITIET_TC entity)
		{
			this.SendPropertyChanging();
			entity.TIEUCHI_SV5T = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAP_SV5T")]
	public partial class CAP_SV5T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MACAP;
		
		private string _TENCAP;
		
		private System.Nullable<int> _SOLUONGDK;
		
		private EntitySet<CHITIET_TC> _CHITIET_TCs;
		
		private EntitySet<PHIEUDK_SV5T> _PHIEUDK_SV5Ts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMACAPChanging(string value);
    partial void OnMACAPChanged();
    partial void OnTENCAPChanging(string value);
    partial void OnTENCAPChanged();
    partial void OnSOLUONGDKChanging(System.Nullable<int> value);
    partial void OnSOLUONGDKChanged();
    #endregion
		
		public CAP_SV5T()
		{
			this._CHITIET_TCs = new EntitySet<CHITIET_TC>(new Action<CHITIET_TC>(this.attach_CHITIET_TCs), new Action<CHITIET_TC>(this.detach_CHITIET_TCs));
			this._PHIEUDK_SV5Ts = new EntitySet<PHIEUDK_SV5T>(new Action<PHIEUDK_SV5T>(this.attach_PHIEUDK_SV5Ts), new Action<PHIEUDK_SV5T>(this.detach_PHIEUDK_SV5Ts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACAP", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACAP
		{
			get
			{
				return this._MACAP;
			}
			set
			{
				if ((this._MACAP != value))
				{
					this.OnMACAPChanging(value);
					this.SendPropertyChanging();
					this._MACAP = value;
					this.SendPropertyChanged("MACAP");
					this.OnMACAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCAP", DbType="NVarChar(50)")]
		public string TENCAP
		{
			get
			{
				return this._TENCAP;
			}
			set
			{
				if ((this._TENCAP != value))
				{
					this.OnTENCAPChanging(value);
					this.SendPropertyChanging();
					this._TENCAP = value;
					this.SendPropertyChanged("TENCAP");
					this.OnTENCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONGDK", DbType="Int")]
		public System.Nullable<int> SOLUONGDK
		{
			get
			{
				return this._SOLUONGDK;
			}
			set
			{
				if ((this._SOLUONGDK != value))
				{
					this.OnSOLUONGDKChanging(value);
					this.SendPropertyChanging();
					this._SOLUONGDK = value;
					this.SendPropertyChanged("SOLUONGDK");
					this.OnSOLUONGDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAP_SV5T_CHITIET_TC", Storage="_CHITIET_TCs", ThisKey="MACAP", OtherKey="MACAP")]
		public EntitySet<CHITIET_TC> CHITIET_TCs
		{
			get
			{
				return this._CHITIET_TCs;
			}
			set
			{
				this._CHITIET_TCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAP_SV5T_PHIEUDK_SV5T", Storage="_PHIEUDK_SV5Ts", ThisKey="MACAP", OtherKey="MACAP")]
		public EntitySet<PHIEUDK_SV5T> PHIEUDK_SV5Ts
		{
			get
			{
				return this._PHIEUDK_SV5Ts;
			}
			set
			{
				this._PHIEUDK_SV5Ts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIET_TCs(CHITIET_TC entity)
		{
			this.SendPropertyChanging();
			entity.CAP_SV5T = this;
		}
		
		private void detach_CHITIET_TCs(CHITIET_TC entity)
		{
			this.SendPropertyChanging();
			entity.CAP_SV5T = null;
		}
		
		private void attach_PHIEUDK_SV5Ts(PHIEUDK_SV5T entity)
		{
			this.SendPropertyChanging();
			entity.CAP_SV5T = this;
		}
		
		private void detach_PHIEUDK_SV5Ts(PHIEUDK_SV5T entity)
		{
			this.SendPropertyChanging();
			entity.CAP_SV5T = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIET_TC")]
	public partial class CHITIET_TC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATC;
		
		private string _MACAP;
		
		private string _NOIDUNG_TC1;
		
		private System.Nullable<System.DateTime> _NGAYCHINHSUA;
		
		private string _NOIDUNG_TC2;
		
		private string _NOIDUNG_TC3;
		
		private string _NOIDUNGTC_4;
		
		private EntityRef<CAP_SV5T> _CAP_SV5T;
		
		private EntityRef<TIEUCHI_SV5T> _TIEUCHI_SV5T;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATCChanging(string value);
    partial void OnMATCChanged();
    partial void OnMACAPChanging(string value);
    partial void OnMACAPChanged();
    partial void OnNOIDUNG_TC1Changing(string value);
    partial void OnNOIDUNG_TC1Changed();
    partial void OnNGAYCHINHSUAChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYCHINHSUAChanged();
    partial void OnNOIDUNG_TC2Changing(string value);
    partial void OnNOIDUNG_TC2Changed();
    partial void OnNOIDUNG_TC3Changing(string value);
    partial void OnNOIDUNG_TC3Changed();
    partial void OnNOIDUNGTC_4Changing(string value);
    partial void OnNOIDUNGTC_4Changed();
    #endregion
		
		public CHITIET_TC()
		{
			this._CAP_SV5T = default(EntityRef<CAP_SV5T>);
			this._TIEUCHI_SV5T = default(EntityRef<TIEUCHI_SV5T>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATC", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATC
		{
			get
			{
				return this._MATC;
			}
			set
			{
				if ((this._MATC != value))
				{
					if (this._TIEUCHI_SV5T.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATCChanging(value);
					this.SendPropertyChanging();
					this._MATC = value;
					this.SendPropertyChanged("MATC");
					this.OnMATCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACAP", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MACAP
		{
			get
			{
				return this._MACAP;
			}
			set
			{
				if ((this._MACAP != value))
				{
					if (this._CAP_SV5T.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACAPChanging(value);
					this.SendPropertyChanging();
					this._MACAP = value;
					this.SendPropertyChanged("MACAP");
					this.OnMACAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG_TC1", DbType="NVarChar(250)")]
		public string NOIDUNG_TC1
		{
			get
			{
				return this._NOIDUNG_TC1;
			}
			set
			{
				if ((this._NOIDUNG_TC1 != value))
				{
					this.OnNOIDUNG_TC1Changing(value);
					this.SendPropertyChanging();
					this._NOIDUNG_TC1 = value;
					this.SendPropertyChanged("NOIDUNG_TC1");
					this.OnNOIDUNG_TC1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYCHINHSUA", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYCHINHSUA
		{
			get
			{
				return this._NGAYCHINHSUA;
			}
			set
			{
				if ((this._NGAYCHINHSUA != value))
				{
					this.OnNGAYCHINHSUAChanging(value);
					this.SendPropertyChanging();
					this._NGAYCHINHSUA = value;
					this.SendPropertyChanged("NGAYCHINHSUA");
					this.OnNGAYCHINHSUAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG_TC2", DbType="NVarChar(500)")]
		public string NOIDUNG_TC2
		{
			get
			{
				return this._NOIDUNG_TC2;
			}
			set
			{
				if ((this._NOIDUNG_TC2 != value))
				{
					this.OnNOIDUNG_TC2Changing(value);
					this.SendPropertyChanging();
					this._NOIDUNG_TC2 = value;
					this.SendPropertyChanged("NOIDUNG_TC2");
					this.OnNOIDUNG_TC2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG_TC3", DbType="NVarChar(500)")]
		public string NOIDUNG_TC3
		{
			get
			{
				return this._NOIDUNG_TC3;
			}
			set
			{
				if ((this._NOIDUNG_TC3 != value))
				{
					this.OnNOIDUNG_TC3Changing(value);
					this.SendPropertyChanging();
					this._NOIDUNG_TC3 = value;
					this.SendPropertyChanged("NOIDUNG_TC3");
					this.OnNOIDUNG_TC3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNGTC_4", DbType="NVarChar(500)")]
		public string NOIDUNGTC_4
		{
			get
			{
				return this._NOIDUNGTC_4;
			}
			set
			{
				if ((this._NOIDUNGTC_4 != value))
				{
					this.OnNOIDUNGTC_4Changing(value);
					this.SendPropertyChanging();
					this._NOIDUNGTC_4 = value;
					this.SendPropertyChanged("NOIDUNGTC_4");
					this.OnNOIDUNGTC_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAP_SV5T_CHITIET_TC", Storage="_CAP_SV5T", ThisKey="MACAP", OtherKey="MACAP", IsForeignKey=true)]
		public CAP_SV5T CAP_SV5T
		{
			get
			{
				return this._CAP_SV5T.Entity;
			}
			set
			{
				CAP_SV5T previousValue = this._CAP_SV5T.Entity;
				if (((previousValue != value) 
							|| (this._CAP_SV5T.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CAP_SV5T.Entity = null;
						previousValue.CHITIET_TCs.Remove(this);
					}
					this._CAP_SV5T.Entity = value;
					if ((value != null))
					{
						value.CHITIET_TCs.Add(this);
						this._MACAP = value.MACAP;
					}
					else
					{
						this._MACAP = default(string);
					}
					this.SendPropertyChanged("CAP_SV5T");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIEUCHI_SV5T_CHITIET_TC", Storage="_TIEUCHI_SV5T", ThisKey="MATC", OtherKey="MATC", IsForeignKey=true)]
		public TIEUCHI_SV5T TIEUCHI_SV5T
		{
			get
			{
				return this._TIEUCHI_SV5T.Entity;
			}
			set
			{
				TIEUCHI_SV5T previousValue = this._TIEUCHI_SV5T.Entity;
				if (((previousValue != value) 
							|| (this._TIEUCHI_SV5T.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TIEUCHI_SV5T.Entity = null;
						previousValue.CHITIET_TCs.Remove(this);
					}
					this._TIEUCHI_SV5T.Entity = value;
					if ((value != null))
					{
						value.CHITIET_TCs.Add(this);
						this._MATC = value.MATC;
					}
					else
					{
						this._MATC = default(string);
					}
					this.SendPropertyChanged("TIEUCHI_SV5T");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHOA")]
	public partial class KHOA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKHOA;
		
		private string _TENKHOA;
		
		private System.Nullable<int> _SOLUONGSV;
		
		private EntitySet<ACCOUNT> _ACCOUNTs;
		
		private EntitySet<LOP> _LOPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHOAChanging(string value);
    partial void OnMAKHOAChanged();
    partial void OnTENKHOAChanging(string value);
    partial void OnTENKHOAChanged();
    partial void OnSOLUONGSVChanging(System.Nullable<int> value);
    partial void OnSOLUONGSVChanged();
    #endregion
		
		public KHOA()
		{
			this._ACCOUNTs = new EntitySet<ACCOUNT>(new Action<ACCOUNT>(this.attach_ACCOUNTs), new Action<ACCOUNT>(this.detach_ACCOUNTs));
			this._LOPs = new EntitySet<LOP>(new Action<LOP>(this.attach_LOPs), new Action<LOP>(this.detach_LOPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHOA", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKHOA
		{
			get
			{
				return this._MAKHOA;
			}
			set
			{
				if ((this._MAKHOA != value))
				{
					this.OnMAKHOAChanging(value);
					this.SendPropertyChanging();
					this._MAKHOA = value;
					this.SendPropertyChanged("MAKHOA");
					this.OnMAKHOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKHOA", DbType="NVarChar(100)")]
		public string TENKHOA
		{
			get
			{
				return this._TENKHOA;
			}
			set
			{
				if ((this._TENKHOA != value))
				{
					this.OnTENKHOAChanging(value);
					this.SendPropertyChanging();
					this._TENKHOA = value;
					this.SendPropertyChanged("TENKHOA");
					this.OnTENKHOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONGSV", DbType="Int")]
		public System.Nullable<int> SOLUONGSV
		{
			get
			{
				return this._SOLUONGSV;
			}
			set
			{
				if ((this._SOLUONGSV != value))
				{
					this.OnSOLUONGSVChanging(value);
					this.SendPropertyChanging();
					this._SOLUONGSV = value;
					this.SendPropertyChanged("SOLUONGSV");
					this.OnSOLUONGSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOA_ACCOUNT", Storage="_ACCOUNTs", ThisKey="MAKHOA", OtherKey="MAKHOA")]
		public EntitySet<ACCOUNT> ACCOUNTs
		{
			get
			{
				return this._ACCOUNTs;
			}
			set
			{
				this._ACCOUNTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOA_LOP", Storage="_LOPs", ThisKey="MAKHOA", OtherKey="MAKHOA")]
		public EntitySet<LOP> LOPs
		{
			get
			{
				return this._LOPs;
			}
			set
			{
				this._LOPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ACCOUNTs(ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.KHOA = this;
		}
		
		private void detach_ACCOUNTs(ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.KHOA = null;
		}
		
		private void attach_LOPs(LOP entity)
		{
			this.SendPropertyChanging();
			entity.KHOA = this;
		}
		
		private void detach_LOPs(LOP entity)
		{
			this.SendPropertyChanging();
			entity.KHOA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KQDANHGIA_ACCOUNT")]
	public partial class KQDANHGIA_ACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<bool> _DIEMRL;
		
		private System.Nullable<bool> _DIEMHOCTAP;
		
		private System.Nullable<bool> _TEST_THELUC;
		
		private System.Nullable<bool> _TN_5NGAYTN;
		
		private System.Nullable<bool> _TN_3CHIENDICHLON;
		
		private System.Nullable<bool> _HN_NGOAINGU;
		
		private System.Nullable<bool> _HN_KYNANG;
		
		private System.Nullable<bool> _UT_KETNAPDANG;
		
		private System.Nullable<bool> _UT_HIENMAU;
		
		private System.Nullable<bool> _UT_BIEUDUONG;
		
		private string _USERNAME;
		
		private string _MaNguoiDanhGia;
		
		private EntityRef<ACCOUNT> _ACCOUNT;
		
		private EntityRef<NGUOIDANHGIA> _NGUOIDANHGIA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDIEMRLChanging(System.Nullable<bool> value);
    partial void OnDIEMRLChanged();
    partial void OnDIEMHOCTAPChanging(System.Nullable<bool> value);
    partial void OnDIEMHOCTAPChanged();
    partial void OnTEST_THELUCChanging(System.Nullable<bool> value);
    partial void OnTEST_THELUCChanged();
    partial void OnTN_5NGAYTNChanging(System.Nullable<bool> value);
    partial void OnTN_5NGAYTNChanged();
    partial void OnTN_3CHIENDICHLONChanging(System.Nullable<bool> value);
    partial void OnTN_3CHIENDICHLONChanged();
    partial void OnHN_NGOAINGUChanging(System.Nullable<bool> value);
    partial void OnHN_NGOAINGUChanged();
    partial void OnHN_KYNANGChanging(System.Nullable<bool> value);
    partial void OnHN_KYNANGChanged();
    partial void OnUT_KETNAPDANGChanging(System.Nullable<bool> value);
    partial void OnUT_KETNAPDANGChanged();
    partial void OnUT_HIENMAUChanging(System.Nullable<bool> value);
    partial void OnUT_HIENMAUChanged();
    partial void OnUT_BIEUDUONGChanging(System.Nullable<bool> value);
    partial void OnUT_BIEUDUONGChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnMaNguoiDanhGiaChanging(string value);
    partial void OnMaNguoiDanhGiaChanged();
    #endregion
		
		public KQDANHGIA_ACCOUNT()
		{
			this._ACCOUNT = default(EntityRef<ACCOUNT>);
			this._NGUOIDANHGIA = default(EntityRef<NGUOIDANHGIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMRL", DbType="Bit")]
		public System.Nullable<bool> DIEMRL
		{
			get
			{
				return this._DIEMRL;
			}
			set
			{
				if ((this._DIEMRL != value))
				{
					this.OnDIEMRLChanging(value);
					this.SendPropertyChanging();
					this._DIEMRL = value;
					this.SendPropertyChanged("DIEMRL");
					this.OnDIEMRLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMHOCTAP", DbType="Bit")]
		public System.Nullable<bool> DIEMHOCTAP
		{
			get
			{
				return this._DIEMHOCTAP;
			}
			set
			{
				if ((this._DIEMHOCTAP != value))
				{
					this.OnDIEMHOCTAPChanging(value);
					this.SendPropertyChanging();
					this._DIEMHOCTAP = value;
					this.SendPropertyChanged("DIEMHOCTAP");
					this.OnDIEMHOCTAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEST_THELUC", DbType="Bit")]
		public System.Nullable<bool> TEST_THELUC
		{
			get
			{
				return this._TEST_THELUC;
			}
			set
			{
				if ((this._TEST_THELUC != value))
				{
					this.OnTEST_THELUCChanging(value);
					this.SendPropertyChanging();
					this._TEST_THELUC = value;
					this.SendPropertyChanged("TEST_THELUC");
					this.OnTEST_THELUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TN_5NGAYTN", DbType="Bit")]
		public System.Nullable<bool> TN_5NGAYTN
		{
			get
			{
				return this._TN_5NGAYTN;
			}
			set
			{
				if ((this._TN_5NGAYTN != value))
				{
					this.OnTN_5NGAYTNChanging(value);
					this.SendPropertyChanging();
					this._TN_5NGAYTN = value;
					this.SendPropertyChanged("TN_5NGAYTN");
					this.OnTN_5NGAYTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TN_3CHIENDICHLON", DbType="Bit")]
		public System.Nullable<bool> TN_3CHIENDICHLON
		{
			get
			{
				return this._TN_3CHIENDICHLON;
			}
			set
			{
				if ((this._TN_3CHIENDICHLON != value))
				{
					this.OnTN_3CHIENDICHLONChanging(value);
					this.SendPropertyChanging();
					this._TN_3CHIENDICHLON = value;
					this.SendPropertyChanged("TN_3CHIENDICHLON");
					this.OnTN_3CHIENDICHLONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HN_NGOAINGU", DbType="Bit")]
		public System.Nullable<bool> HN_NGOAINGU
		{
			get
			{
				return this._HN_NGOAINGU;
			}
			set
			{
				if ((this._HN_NGOAINGU != value))
				{
					this.OnHN_NGOAINGUChanging(value);
					this.SendPropertyChanging();
					this._HN_NGOAINGU = value;
					this.SendPropertyChanged("HN_NGOAINGU");
					this.OnHN_NGOAINGUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HN_KYNANG", DbType="Bit")]
		public System.Nullable<bool> HN_KYNANG
		{
			get
			{
				return this._HN_KYNANG;
			}
			set
			{
				if ((this._HN_KYNANG != value))
				{
					this.OnHN_KYNANGChanging(value);
					this.SendPropertyChanging();
					this._HN_KYNANG = value;
					this.SendPropertyChanged("HN_KYNANG");
					this.OnHN_KYNANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UT_KETNAPDANG", DbType="Bit")]
		public System.Nullable<bool> UT_KETNAPDANG
		{
			get
			{
				return this._UT_KETNAPDANG;
			}
			set
			{
				if ((this._UT_KETNAPDANG != value))
				{
					this.OnUT_KETNAPDANGChanging(value);
					this.SendPropertyChanging();
					this._UT_KETNAPDANG = value;
					this.SendPropertyChanged("UT_KETNAPDANG");
					this.OnUT_KETNAPDANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UT_HIENMAU", DbType="Bit")]
		public System.Nullable<bool> UT_HIENMAU
		{
			get
			{
				return this._UT_HIENMAU;
			}
			set
			{
				if ((this._UT_HIENMAU != value))
				{
					this.OnUT_HIENMAUChanging(value);
					this.SendPropertyChanging();
					this._UT_HIENMAU = value;
					this.SendPropertyChanged("UT_HIENMAU");
					this.OnUT_HIENMAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UT_BIEUDUONG", DbType="Bit")]
		public System.Nullable<bool> UT_BIEUDUONG
		{
			get
			{
				return this._UT_BIEUDUONG;
			}
			set
			{
				if ((this._UT_BIEUDUONG != value))
				{
					this.OnUT_BIEUDUONGChanging(value);
					this.SendPropertyChanging();
					this._UT_BIEUDUONG = value;
					this.SendPropertyChanged("UT_BIEUDUONG");
					this.OnUT_BIEUDUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					if (this._ACCOUNT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDanhGia", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDanhGia
		{
			get
			{
				return this._MaNguoiDanhGia;
			}
			set
			{
				if ((this._MaNguoiDanhGia != value))
				{
					if (this._NGUOIDANHGIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDanhGia = value;
					this.SendPropertyChanged("MaNguoiDanhGia");
					this.OnMaNguoiDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_KQDANHGIA_ACCOUNT", Storage="_ACCOUNT", ThisKey="USERNAME", OtherKey="USERNAME", IsForeignKey=true)]
		public ACCOUNT ACCOUNT
		{
			get
			{
				return this._ACCOUNT.Entity;
			}
			set
			{
				ACCOUNT previousValue = this._ACCOUNT.Entity;
				if (((previousValue != value) 
							|| (this._ACCOUNT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ACCOUNT.Entity = null;
						previousValue.KQDANHGIA_ACCOUNTs.Remove(this);
					}
					this._ACCOUNT.Entity = value;
					if ((value != null))
					{
						value.KQDANHGIA_ACCOUNTs.Add(this);
						this._USERNAME = value.USERNAME;
					}
					else
					{
						this._USERNAME = default(string);
					}
					this.SendPropertyChanged("ACCOUNT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDANHGIA_KQDANHGIA_ACCOUNT", Storage="_NGUOIDANHGIA", ThisKey="MaNguoiDanhGia", OtherKey="MaNguoiDanhGia", IsForeignKey=true)]
		public NGUOIDANHGIA NGUOIDANHGIA
		{
			get
			{
				return this._NGUOIDANHGIA.Entity;
			}
			set
			{
				NGUOIDANHGIA previousValue = this._NGUOIDANHGIA.Entity;
				if (((previousValue != value) 
							|| (this._NGUOIDANHGIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGUOIDANHGIA.Entity = null;
						previousValue.KQDANHGIA_ACCOUNTs.Remove(this);
					}
					this._NGUOIDANHGIA.Entity = value;
					if ((value != null))
					{
						value.KQDANHGIA_ACCOUNTs.Add(this);
						this._MaNguoiDanhGia = value.MaNguoiDanhGia;
					}
					else
					{
						this._MaNguoiDanhGia = default(string);
					}
					this.SendPropertyChanged("NGUOIDANHGIA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LHTT")]
	public partial class LHTT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _STT;
		
		private string _MALOP;
		
		private EntityRef<LOP> _LOP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(byte value);
    partial void OnSTTChanged();
    partial void OnMALOPChanging(string value);
    partial void OnMALOPChanged();
    #endregion
		
		public LHTT()
		{
			this._LOP = default(EntityRef<LOP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					if (this._LOP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOPChanging(value);
					this.SendPropertyChanging();
					this._MALOP = value;
					this.SendPropertyChanged("MALOP");
					this.OnMALOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_LHTT", Storage="_LOP", ThisKey="MALOP", OtherKey="MALOP", IsForeignKey=true)]
		public LOP LOP
		{
			get
			{
				return this._LOP.Entity;
			}
			set
			{
				LOP previousValue = this._LOP.Entity;
				if (((previousValue != value) 
							|| (this._LOP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOP.Entity = null;
						previousValue.LHTTs.Remove(this);
					}
					this._LOP.Entity = value;
					if ((value != null))
					{
						value.LHTTs.Add(this);
						this._MALOP = value.MALOP;
					}
					else
					{
						this._MALOP = default(string);
					}
					this.SendPropertyChanged("LOP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOP")]
	public partial class LOP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOP;
		
		private string _MAKHOA;
		
		private System.Nullable<int> _SOLUONG_SV;
		
		private EntitySet<LHTT> _LHTTs;
		
		private EntityRef<KHOA> _KHOA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOPChanging(string value);
    partial void OnMALOPChanged();
    partial void OnMAKHOAChanging(string value);
    partial void OnMAKHOAChanged();
    partial void OnSOLUONG_SVChanging(System.Nullable<int> value);
    partial void OnSOLUONG_SVChanged();
    #endregion
		
		public LOP()
		{
			this._LHTTs = new EntitySet<LHTT>(new Action<LHTT>(this.attach_LHTTs), new Action<LHTT>(this.detach_LHTTs));
			this._KHOA = default(EntityRef<KHOA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOP", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOP
		{
			get
			{
				return this._MALOP;
			}
			set
			{
				if ((this._MALOP != value))
				{
					this.OnMALOPChanging(value);
					this.SendPropertyChanging();
					this._MALOP = value;
					this.SendPropertyChanged("MALOP");
					this.OnMALOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHOA", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MAKHOA
		{
			get
			{
				return this._MAKHOA;
			}
			set
			{
				if ((this._MAKHOA != value))
				{
					if (this._KHOA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHOAChanging(value);
					this.SendPropertyChanging();
					this._MAKHOA = value;
					this.SendPropertyChanged("MAKHOA");
					this.OnMAKHOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG_SV", DbType="Int")]
		public System.Nullable<int> SOLUONG_SV
		{
			get
			{
				return this._SOLUONG_SV;
			}
			set
			{
				if ((this._SOLUONG_SV != value))
				{
					this.OnSOLUONG_SVChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG_SV = value;
					this.SendPropertyChanged("SOLUONG_SV");
					this.OnSOLUONG_SVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_LHTT", Storage="_LHTTs", ThisKey="MALOP", OtherKey="MALOP")]
		public EntitySet<LHTT> LHTTs
		{
			get
			{
				return this._LHTTs;
			}
			set
			{
				this._LHTTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOA_LOP", Storage="_KHOA", ThisKey="MAKHOA", OtherKey="MAKHOA", IsForeignKey=true)]
		public KHOA KHOA
		{
			get
			{
				return this._KHOA.Entity;
			}
			set
			{
				KHOA previousValue = this._KHOA.Entity;
				if (((previousValue != value) 
							|| (this._KHOA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOA.Entity = null;
						previousValue.LOPs.Remove(this);
					}
					this._KHOA.Entity = value;
					if ((value != null))
					{
						value.LOPs.Add(this);
						this._MAKHOA = value.MAKHOA;
					}
					else
					{
						this._MAKHOA = default(string);
					}
					this.SendPropertyChanged("KHOA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LHTTs(LHTT entity)
		{
			this.SendPropertyChanging();
			entity.LOP = this;
		}
		
		private void detach_LHTTs(LHTT entity)
		{
			this.SendPropertyChanging();
			entity.LOP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDANHGIA")]
	public partial class NGUOIDANHGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguoiDanhGia;
		
		private string _TenLoai;
		
		private EntitySet<KQDANHGIA_ACCOUNT> _KQDANHGIA_ACCOUNTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDanhGiaChanging(string value);
    partial void OnMaNguoiDanhGiaChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public NGUOIDANHGIA()
		{
			this._KQDANHGIA_ACCOUNTs = new EntitySet<KQDANHGIA_ACCOUNT>(new Action<KQDANHGIA_ACCOUNT>(this.attach_KQDANHGIA_ACCOUNTs), new Action<KQDANHGIA_ACCOUNT>(this.detach_KQDANHGIA_ACCOUNTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDanhGia", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDanhGia
		{
			get
			{
				return this._MaNguoiDanhGia;
			}
			set
			{
				if ((this._MaNguoiDanhGia != value))
				{
					this.OnMaNguoiDanhGiaChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDanhGia = value;
					this.SendPropertyChanged("MaNguoiDanhGia");
					this.OnMaNguoiDanhGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(100)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGUOIDANHGIA_KQDANHGIA_ACCOUNT", Storage="_KQDANHGIA_ACCOUNTs", ThisKey="MaNguoiDanhGia", OtherKey="MaNguoiDanhGia")]
		public EntitySet<KQDANHGIA_ACCOUNT> KQDANHGIA_ACCOUNTs
		{
			get
			{
				return this._KQDANHGIA_ACCOUNTs;
			}
			set
			{
				this._KQDANHGIA_ACCOUNTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KQDANHGIA_ACCOUNTs(KQDANHGIA_ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDANHGIA = this;
		}
		
		private void detach_KQDANHGIA_ACCOUNTs(KQDANHGIA_ACCOUNT entity)
		{
			this.SendPropertyChanging();
			entity.NGUOIDANHGIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUDK_SV5T")]
	public partial class PHIEUDK_SV5T : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SOPHIEUDK;
		
		private System.Nullable<System.DateTime> _NGAYLAP;
		
		private System.Nullable<int> _DRL_HK1;
		
		private System.Nullable<int> _DRL_HK2;
		
		private System.Nullable<int> _DRL_TB;
		
		private string _KQ_CHATLUONGDOANVIEN;
		
		private System.Nullable<bool> _DD_THANHNIENTTLAMTHEOLOIBAC;
		
		private System.Nullable<bool> _DD_HOITHI_TTHCM;
		
		private System.Nullable<double> _DIEMHK1;
		
		private System.Nullable<double> _DIEMHK2;
		
		private System.Nullable<double> _DIEMTB;
		
		private System.Nullable<bool> _HT_BAIVIETKH;
		
		private System.Nullable<char> _HT_NCKH;
		
		private System.Nullable<bool> _HT_GIAITHIHOCTHUAT;
		
		private string _TEN_THIHOCTHUAT;
		
		private System.Nullable<bool> _TL_SVKHOE;
		
		private System.Nullable<bool> _TL_TV_DOITUYENTDTT;
		
		private System.Nullable<bool> _DATGIAIHOITHAOCACCAP;
		
		private string _TEN_CAPHOITHAO;
		
		private System.Data.Linq.Binary _TN_THAMGIACHIENDICHLON;
		
		private System.Nullable<bool> _TN_5HDTN_NAM;
		
		private System.Nullable<bool> _HN_AV_B1;
		
		private string _TEN_AV_KHAC;
		
		private System.Nullable<bool> _HN_GIAOLUUQT;
		
		private System.Nullable<bool> _HN_GIAICUOCTHI_NNgu;
		
		private System.Nullable<bool> _HN_1KHOAHOCKYNANG;
		
		private System.Nullable<bool> _HN_3BUOI_HOITHAOKYNANG;
		
		private System.Nullable<bool> _HN_THAMGIA_HDHOINHAP;
		
		private System.Nullable<bool> _UT_KETNAPDANG;
		
		private System.Nullable<bool> _UT_HIENMAU;
		
		private System.Nullable<bool> _UT_BIEUDUONG_KHENTHUONG;
		
		private string _KHOKHAN_KIENNGHI;
		
		private string _MACAP;
		
		private string _USERNAME;
		
		private EntityRef<CAP_SV5T> _CAP_SV5T;
		
		private EntityRef<ACCOUNT> _ACCOUNT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSOPHIEUDKChanging(int value);
    partial void OnSOPHIEUDKChanged();
    partial void OnNGAYLAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPChanged();
    partial void OnDRL_HK1Changing(System.Nullable<int> value);
    partial void OnDRL_HK1Changed();
    partial void OnDRL_HK2Changing(System.Nullable<int> value);
    partial void OnDRL_HK2Changed();
    partial void OnDRL_TBChanging(System.Nullable<int> value);
    partial void OnDRL_TBChanged();
    partial void OnKQ_CHATLUONGDOANVIENChanging(string value);
    partial void OnKQ_CHATLUONGDOANVIENChanged();
    partial void OnDD_THANHNIENTTLAMTHEOLOIBACChanging(System.Nullable<bool> value);
    partial void OnDD_THANHNIENTTLAMTHEOLOIBACChanged();
    partial void OnDD_HOITHI_TTHCMChanging(System.Nullable<bool> value);
    partial void OnDD_HOITHI_TTHCMChanged();
    partial void OnDIEMHK1Changing(System.Nullable<double> value);
    partial void OnDIEMHK1Changed();
    partial void OnDIEMHK2Changing(System.Nullable<double> value);
    partial void OnDIEMHK2Changed();
    partial void OnDIEMTBChanging(System.Nullable<double> value);
    partial void OnDIEMTBChanged();
    partial void OnHT_BAIVIETKHChanging(System.Nullable<bool> value);
    partial void OnHT_BAIVIETKHChanged();
    partial void OnHT_NCKHChanging(System.Nullable<char> value);
    partial void OnHT_NCKHChanged();
    partial void OnHT_GIAITHIHOCTHUATChanging(System.Nullable<bool> value);
    partial void OnHT_GIAITHIHOCTHUATChanged();
    partial void OnTEN_THIHOCTHUATChanging(string value);
    partial void OnTEN_THIHOCTHUATChanged();
    partial void OnTL_SVKHOEChanging(System.Nullable<bool> value);
    partial void OnTL_SVKHOEChanged();
    partial void OnTL_TV_DOITUYENTDTTChanging(System.Nullable<bool> value);
    partial void OnTL_TV_DOITUYENTDTTChanged();
    partial void OnDATGIAIHOITHAOCACCAPChanging(System.Nullable<bool> value);
    partial void OnDATGIAIHOITHAOCACCAPChanged();
    partial void OnTEN_CAPHOITHAOChanging(string value);
    partial void OnTEN_CAPHOITHAOChanged();
    partial void OnTN_THAMGIACHIENDICHLONChanging(System.Data.Linq.Binary value);
    partial void OnTN_THAMGIACHIENDICHLONChanged();
    partial void OnTN_5HDTN_NAMChanging(System.Nullable<bool> value);
    partial void OnTN_5HDTN_NAMChanged();
    partial void OnHN_AV_B1Changing(System.Nullable<bool> value);
    partial void OnHN_AV_B1Changed();
    partial void OnTEN_AV_KHACChanging(string value);
    partial void OnTEN_AV_KHACChanged();
    partial void OnHN_GIAOLUUQTChanging(System.Nullable<bool> value);
    partial void OnHN_GIAOLUUQTChanged();
    partial void OnHN_GIAICUOCTHI_NNguChanging(System.Nullable<bool> value);
    partial void OnHN_GIAICUOCTHI_NNguChanged();
    partial void OnHN_1KHOAHOCKYNANGChanging(System.Nullable<bool> value);
    partial void OnHN_1KHOAHOCKYNANGChanged();
    partial void OnHN_3BUOI_HOITHAOKYNANGChanging(System.Nullable<bool> value);
    partial void OnHN_3BUOI_HOITHAOKYNANGChanged();
    partial void OnHN_THAMGIA_HDHOINHAPChanging(System.Nullable<bool> value);
    partial void OnHN_THAMGIA_HDHOINHAPChanged();
    partial void OnUT_KETNAPDANGChanging(System.Nullable<bool> value);
    partial void OnUT_KETNAPDANGChanged();
    partial void OnUT_HIENMAUChanging(System.Nullable<bool> value);
    partial void OnUT_HIENMAUChanged();
    partial void OnUT_BIEUDUONG_KHENTHUONGChanging(System.Nullable<bool> value);
    partial void OnUT_BIEUDUONG_KHENTHUONGChanged();
    partial void OnKHOKHAN_KIENNGHIChanging(string value);
    partial void OnKHOKHAN_KIENNGHIChanged();
    partial void OnMACAPChanging(string value);
    partial void OnMACAPChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    #endregion
		
		public PHIEUDK_SV5T()
		{
			this._CAP_SV5T = default(EntityRef<CAP_SV5T>);
			this._ACCOUNT = default(EntityRef<ACCOUNT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOPHIEUDK", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SOPHIEUDK
		{
			get
			{
				return this._SOPHIEUDK;
			}
			set
			{
				if ((this._SOPHIEUDK != value))
				{
					this.OnSOPHIEUDKChanging(value);
					this.SendPropertyChanging();
					this._SOPHIEUDK = value;
					this.SendPropertyChanged("SOPHIEUDK");
					this.OnSOPHIEUDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRL_HK1", DbType="Int")]
		public System.Nullable<int> DRL_HK1
		{
			get
			{
				return this._DRL_HK1;
			}
			set
			{
				if ((this._DRL_HK1 != value))
				{
					this.OnDRL_HK1Changing(value);
					this.SendPropertyChanging();
					this._DRL_HK1 = value;
					this.SendPropertyChanged("DRL_HK1");
					this.OnDRL_HK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRL_HK2", DbType="Int")]
		public System.Nullable<int> DRL_HK2
		{
			get
			{
				return this._DRL_HK2;
			}
			set
			{
				if ((this._DRL_HK2 != value))
				{
					this.OnDRL_HK2Changing(value);
					this.SendPropertyChanging();
					this._DRL_HK2 = value;
					this.SendPropertyChanged("DRL_HK2");
					this.OnDRL_HK2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DRL_TB", DbType="Int")]
		public System.Nullable<int> DRL_TB
		{
			get
			{
				return this._DRL_TB;
			}
			set
			{
				if ((this._DRL_TB != value))
				{
					this.OnDRL_TBChanging(value);
					this.SendPropertyChanging();
					this._DRL_TB = value;
					this.SendPropertyChanged("DRL_TB");
					this.OnDRL_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KQ_CHATLUONGDOANVIEN", DbType="NVarChar(30)")]
		public string KQ_CHATLUONGDOANVIEN
		{
			get
			{
				return this._KQ_CHATLUONGDOANVIEN;
			}
			set
			{
				if ((this._KQ_CHATLUONGDOANVIEN != value))
				{
					this.OnKQ_CHATLUONGDOANVIENChanging(value);
					this.SendPropertyChanging();
					this._KQ_CHATLUONGDOANVIEN = value;
					this.SendPropertyChanged("KQ_CHATLUONGDOANVIEN");
					this.OnKQ_CHATLUONGDOANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DD_THANHNIENTTLAMTHEOLOIBAC", DbType="Bit")]
		public System.Nullable<bool> DD_THANHNIENTTLAMTHEOLOIBAC
		{
			get
			{
				return this._DD_THANHNIENTTLAMTHEOLOIBAC;
			}
			set
			{
				if ((this._DD_THANHNIENTTLAMTHEOLOIBAC != value))
				{
					this.OnDD_THANHNIENTTLAMTHEOLOIBACChanging(value);
					this.SendPropertyChanging();
					this._DD_THANHNIENTTLAMTHEOLOIBAC = value;
					this.SendPropertyChanged("DD_THANHNIENTTLAMTHEOLOIBAC");
					this.OnDD_THANHNIENTTLAMTHEOLOIBACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DD_HOITHI_TTHCM", DbType="Bit")]
		public System.Nullable<bool> DD_HOITHI_TTHCM
		{
			get
			{
				return this._DD_HOITHI_TTHCM;
			}
			set
			{
				if ((this._DD_HOITHI_TTHCM != value))
				{
					this.OnDD_HOITHI_TTHCMChanging(value);
					this.SendPropertyChanging();
					this._DD_HOITHI_TTHCM = value;
					this.SendPropertyChanged("DD_HOITHI_TTHCM");
					this.OnDD_HOITHI_TTHCMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMHK1", DbType="Float")]
		public System.Nullable<double> DIEMHK1
		{
			get
			{
				return this._DIEMHK1;
			}
			set
			{
				if ((this._DIEMHK1 != value))
				{
					this.OnDIEMHK1Changing(value);
					this.SendPropertyChanging();
					this._DIEMHK1 = value;
					this.SendPropertyChanged("DIEMHK1");
					this.OnDIEMHK1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMHK2", DbType="Float")]
		public System.Nullable<double> DIEMHK2
		{
			get
			{
				return this._DIEMHK2;
			}
			set
			{
				if ((this._DIEMHK2 != value))
				{
					this.OnDIEMHK2Changing(value);
					this.SendPropertyChanging();
					this._DIEMHK2 = value;
					this.SendPropertyChanged("DIEMHK2");
					this.OnDIEMHK2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMTB", DbType="Float")]
		public System.Nullable<double> DIEMTB
		{
			get
			{
				return this._DIEMTB;
			}
			set
			{
				if ((this._DIEMTB != value))
				{
					this.OnDIEMTBChanging(value);
					this.SendPropertyChanging();
					this._DIEMTB = value;
					this.SendPropertyChanged("DIEMTB");
					this.OnDIEMTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HT_BAIVIETKH", DbType="Bit")]
		public System.Nullable<bool> HT_BAIVIETKH
		{
			get
			{
				return this._HT_BAIVIETKH;
			}
			set
			{
				if ((this._HT_BAIVIETKH != value))
				{
					this.OnHT_BAIVIETKHChanging(value);
					this.SendPropertyChanging();
					this._HT_BAIVIETKH = value;
					this.SendPropertyChanged("HT_BAIVIETKH");
					this.OnHT_BAIVIETKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HT_NCKH", DbType="Char(1)")]
		public System.Nullable<char> HT_NCKH
		{
			get
			{
				return this._HT_NCKH;
			}
			set
			{
				if ((this._HT_NCKH != value))
				{
					this.OnHT_NCKHChanging(value);
					this.SendPropertyChanging();
					this._HT_NCKH = value;
					this.SendPropertyChanged("HT_NCKH");
					this.OnHT_NCKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HT_GIAITHIHOCTHUAT", DbType="Bit")]
		public System.Nullable<bool> HT_GIAITHIHOCTHUAT
		{
			get
			{
				return this._HT_GIAITHIHOCTHUAT;
			}
			set
			{
				if ((this._HT_GIAITHIHOCTHUAT != value))
				{
					this.OnHT_GIAITHIHOCTHUATChanging(value);
					this.SendPropertyChanging();
					this._HT_GIAITHIHOCTHUAT = value;
					this.SendPropertyChanged("HT_GIAITHIHOCTHUAT");
					this.OnHT_GIAITHIHOCTHUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_THIHOCTHUAT", DbType="NVarChar(200)")]
		public string TEN_THIHOCTHUAT
		{
			get
			{
				return this._TEN_THIHOCTHUAT;
			}
			set
			{
				if ((this._TEN_THIHOCTHUAT != value))
				{
					this.OnTEN_THIHOCTHUATChanging(value);
					this.SendPropertyChanging();
					this._TEN_THIHOCTHUAT = value;
					this.SendPropertyChanged("TEN_THIHOCTHUAT");
					this.OnTEN_THIHOCTHUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_SVKHOE", DbType="Bit")]
		public System.Nullable<bool> TL_SVKHOE
		{
			get
			{
				return this._TL_SVKHOE;
			}
			set
			{
				if ((this._TL_SVKHOE != value))
				{
					this.OnTL_SVKHOEChanging(value);
					this.SendPropertyChanging();
					this._TL_SVKHOE = value;
					this.SendPropertyChanged("TL_SVKHOE");
					this.OnTL_SVKHOEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TL_TV_DOITUYENTDTT", DbType="Bit")]
		public System.Nullable<bool> TL_TV_DOITUYENTDTT
		{
			get
			{
				return this._TL_TV_DOITUYENTDTT;
			}
			set
			{
				if ((this._TL_TV_DOITUYENTDTT != value))
				{
					this.OnTL_TV_DOITUYENTDTTChanging(value);
					this.SendPropertyChanging();
					this._TL_TV_DOITUYENTDTT = value;
					this.SendPropertyChanged("TL_TV_DOITUYENTDTT");
					this.OnTL_TV_DOITUYENTDTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATGIAIHOITHAOCACCAP", DbType="Bit")]
		public System.Nullable<bool> DATGIAIHOITHAOCACCAP
		{
			get
			{
				return this._DATGIAIHOITHAOCACCAP;
			}
			set
			{
				if ((this._DATGIAIHOITHAOCACCAP != value))
				{
					this.OnDATGIAIHOITHAOCACCAPChanging(value);
					this.SendPropertyChanging();
					this._DATGIAIHOITHAOCACCAP = value;
					this.SendPropertyChanged("DATGIAIHOITHAOCACCAP");
					this.OnDATGIAIHOITHAOCACCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_CAPHOITHAO", DbType="NVarChar(100)")]
		public string TEN_CAPHOITHAO
		{
			get
			{
				return this._TEN_CAPHOITHAO;
			}
			set
			{
				if ((this._TEN_CAPHOITHAO != value))
				{
					this.OnTEN_CAPHOITHAOChanging(value);
					this.SendPropertyChanging();
					this._TEN_CAPHOITHAO = value;
					this.SendPropertyChanged("TEN_CAPHOITHAO");
					this.OnTEN_CAPHOITHAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TN_THAMGIACHIENDICHLON", DbType="Binary(1)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary TN_THAMGIACHIENDICHLON
		{
			get
			{
				return this._TN_THAMGIACHIENDICHLON;
			}
			set
			{
				if ((this._TN_THAMGIACHIENDICHLON != value))
				{
					this.OnTN_THAMGIACHIENDICHLONChanging(value);
					this.SendPropertyChanging();
					this._TN_THAMGIACHIENDICHLON = value;
					this.SendPropertyChanged("TN_THAMGIACHIENDICHLON");
					this.OnTN_THAMGIACHIENDICHLONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TN_5HDTN_NAM", DbType="Bit")]
		public System.Nullable<bool> TN_5HDTN_NAM
		{
			get
			{
				return this._TN_5HDTN_NAM;
			}
			set
			{
				if ((this._TN_5HDTN_NAM != value))
				{
					this.OnTN_5HDTN_NAMChanging(value);
					this.SendPropertyChanging();
					this._TN_5HDTN_NAM = value;
					this.SendPropertyChanged("TN_5HDTN_NAM");
					this.OnTN_5HDTN_NAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HN_AV_B1", DbType="Bit")]
		public System.Nullable<bool> HN_AV_B1
		{
			get
			{
				return this._HN_AV_B1;
			}
			set
			{
				if ((this._HN_AV_B1 != value))
				{
					this.OnHN_AV_B1Changing(value);
					this.SendPropertyChanging();
					this._HN_AV_B1 = value;
					this.SendPropertyChanged("HN_AV_B1");
					this.OnHN_AV_B1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_AV_KHAC", DbType="VarChar(50)")]
		public string TEN_AV_KHAC
		{
			get
			{
				return this._TEN_AV_KHAC;
			}
			set
			{
				if ((this._TEN_AV_KHAC != value))
				{
					this.OnTEN_AV_KHACChanging(value);
					this.SendPropertyChanging();
					this._TEN_AV_KHAC = value;
					this.SendPropertyChanged("TEN_AV_KHAC");
					this.OnTEN_AV_KHACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HN_GIAOLUUQT", DbType="Bit")]
		public System.Nullable<bool> HN_GIAOLUUQT
		{
			get
			{
				return this._HN_GIAOLUUQT;
			}
			set
			{
				if ((this._HN_GIAOLUUQT != value))
				{
					this.OnHN_GIAOLUUQTChanging(value);
					this.SendPropertyChanging();
					this._HN_GIAOLUUQT = value;
					this.SendPropertyChanged("HN_GIAOLUUQT");
					this.OnHN_GIAOLUUQTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HN_GIAICUOCTHI_NNgu", DbType="Bit")]
		public System.Nullable<bool> HN_GIAICUOCTHI_NNgu
		{
			get
			{
				return this._HN_GIAICUOCTHI_NNgu;
			}
			set
			{
				if ((this._HN_GIAICUOCTHI_NNgu != value))
				{
					this.OnHN_GIAICUOCTHI_NNguChanging(value);
					this.SendPropertyChanging();
					this._HN_GIAICUOCTHI_NNgu = value;
					this.SendPropertyChanged("HN_GIAICUOCTHI_NNgu");
					this.OnHN_GIAICUOCTHI_NNguChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HN_1KHOAHOCKYNANG", DbType="Bit")]
		public System.Nullable<bool> HN_1KHOAHOCKYNANG
		{
			get
			{
				return this._HN_1KHOAHOCKYNANG;
			}
			set
			{
				if ((this._HN_1KHOAHOCKYNANG != value))
				{
					this.OnHN_1KHOAHOCKYNANGChanging(value);
					this.SendPropertyChanging();
					this._HN_1KHOAHOCKYNANG = value;
					this.SendPropertyChanged("HN_1KHOAHOCKYNANG");
					this.OnHN_1KHOAHOCKYNANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HN_3BUOI_HOITHAOKYNANG", DbType="Bit")]
		public System.Nullable<bool> HN_3BUOI_HOITHAOKYNANG
		{
			get
			{
				return this._HN_3BUOI_HOITHAOKYNANG;
			}
			set
			{
				if ((this._HN_3BUOI_HOITHAOKYNANG != value))
				{
					this.OnHN_3BUOI_HOITHAOKYNANGChanging(value);
					this.SendPropertyChanging();
					this._HN_3BUOI_HOITHAOKYNANG = value;
					this.SendPropertyChanged("HN_3BUOI_HOITHAOKYNANG");
					this.OnHN_3BUOI_HOITHAOKYNANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HN_THAMGIA_HDHOINHAP", DbType="Bit")]
		public System.Nullable<bool> HN_THAMGIA_HDHOINHAP
		{
			get
			{
				return this._HN_THAMGIA_HDHOINHAP;
			}
			set
			{
				if ((this._HN_THAMGIA_HDHOINHAP != value))
				{
					this.OnHN_THAMGIA_HDHOINHAPChanging(value);
					this.SendPropertyChanging();
					this._HN_THAMGIA_HDHOINHAP = value;
					this.SendPropertyChanged("HN_THAMGIA_HDHOINHAP");
					this.OnHN_THAMGIA_HDHOINHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UT_KETNAPDANG", DbType="Bit")]
		public System.Nullable<bool> UT_KETNAPDANG
		{
			get
			{
				return this._UT_KETNAPDANG;
			}
			set
			{
				if ((this._UT_KETNAPDANG != value))
				{
					this.OnUT_KETNAPDANGChanging(value);
					this.SendPropertyChanging();
					this._UT_KETNAPDANG = value;
					this.SendPropertyChanged("UT_KETNAPDANG");
					this.OnUT_KETNAPDANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UT_HIENMAU", DbType="Bit")]
		public System.Nullable<bool> UT_HIENMAU
		{
			get
			{
				return this._UT_HIENMAU;
			}
			set
			{
				if ((this._UT_HIENMAU != value))
				{
					this.OnUT_HIENMAUChanging(value);
					this.SendPropertyChanging();
					this._UT_HIENMAU = value;
					this.SendPropertyChanged("UT_HIENMAU");
					this.OnUT_HIENMAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UT_BIEUDUONG_KHENTHUONG", DbType="Bit")]
		public System.Nullable<bool> UT_BIEUDUONG_KHENTHUONG
		{
			get
			{
				return this._UT_BIEUDUONG_KHENTHUONG;
			}
			set
			{
				if ((this._UT_BIEUDUONG_KHENTHUONG != value))
				{
					this.OnUT_BIEUDUONG_KHENTHUONGChanging(value);
					this.SendPropertyChanging();
					this._UT_BIEUDUONG_KHENTHUONG = value;
					this.SendPropertyChanged("UT_BIEUDUONG_KHENTHUONG");
					this.OnUT_BIEUDUONG_KHENTHUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[KHOKHAN-KIENNGHI]", Storage="_KHOKHAN_KIENNGHI", DbType="NVarChar(500)")]
		public string KHOKHAN_KIENNGHI
		{
			get
			{
				return this._KHOKHAN_KIENNGHI;
			}
			set
			{
				if ((this._KHOKHAN_KIENNGHI != value))
				{
					this.OnKHOKHAN_KIENNGHIChanging(value);
					this.SendPropertyChanging();
					this._KHOKHAN_KIENNGHI = value;
					this.SendPropertyChanged("KHOKHAN_KIENNGHI");
					this.OnKHOKHAN_KIENNGHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACAP", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MACAP
		{
			get
			{
				return this._MACAP;
			}
			set
			{
				if ((this._MACAP != value))
				{
					if (this._CAP_SV5T.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMACAPChanging(value);
					this.SendPropertyChanging();
					this._MACAP = value;
					this.SendPropertyChanged("MACAP");
					this.OnMACAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					if (this._ACCOUNT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CAP_SV5T_PHIEUDK_SV5T", Storage="_CAP_SV5T", ThisKey="MACAP", OtherKey="MACAP", IsForeignKey=true)]
		public CAP_SV5T CAP_SV5T
		{
			get
			{
				return this._CAP_SV5T.Entity;
			}
			set
			{
				CAP_SV5T previousValue = this._CAP_SV5T.Entity;
				if (((previousValue != value) 
							|| (this._CAP_SV5T.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CAP_SV5T.Entity = null;
						previousValue.PHIEUDK_SV5Ts.Remove(this);
					}
					this._CAP_SV5T.Entity = value;
					if ((value != null))
					{
						value.PHIEUDK_SV5Ts.Add(this);
						this._MACAP = value.MACAP;
					}
					else
					{
						this._MACAP = default(string);
					}
					this.SendPropertyChanged("CAP_SV5T");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNT_PHIEUDK_SV5T", Storage="_ACCOUNT", ThisKey="USERNAME", OtherKey="USERNAME", IsForeignKey=true)]
		public ACCOUNT ACCOUNT
		{
			get
			{
				return this._ACCOUNT.Entity;
			}
			set
			{
				ACCOUNT previousValue = this._ACCOUNT.Entity;
				if (((previousValue != value) 
							|| (this._ACCOUNT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ACCOUNT.Entity = null;
						previousValue.PHIEUDK_SV5Ts.Remove(this);
					}
					this._ACCOUNT.Entity = value;
					if ((value != null))
					{
						value.PHIEUDK_SV5Ts.Add(this);
						this._USERNAME = value.USERNAME;
					}
					else
					{
						this._USERNAME = default(string);
					}
					this.SendPropertyChanged("ACCOUNT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
