<?xml version="1.0" encoding="utf-8"?><Database Name="DOANCOSO" Class="DOANCOSODataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=TUANMF\SQLEXPRESS;Initial Catalog=DOANCOSO;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DOANCOSOConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ACCOUNT" Member="ACCOUNTs">
    <Type Name="ACCOUNT">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKHOA" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PASSWORD" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="MALOAI" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="QUYEN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ACCOUNT_KQDANHGIA_ACCOUNT" Member="KQDANHGIA_ACCOUNTs" ThisKey="USERNAME" OtherKey="USERNAME" Type="KQDANHGIA_ACCOUNT" />
      <Association Name="ACCOUNT_PHIEUDK_SV5T" Member="PHIEUDK_SV5Ts" ThisKey="USERNAME" OtherKey="USERNAME" Type="PHIEUDK_SV5T" />
      <Association Name="KHOA_ACCOUNT" Member="KHOA" ThisKey="MAKHOA" OtherKey="MAKHOA" Type="KHOA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TIEUCHI_SV5T" Member="TIEUCHI_SV5Ts">
    <Type Name="TIEUCHI_SV5T">
      <Column Name="MATC" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTC" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TIEUCHI_SV5T_CHITIET_TC" Member="CHITIET_TCs" ThisKey="MATC" OtherKey="MATC" Type="CHITIET_TC" />
    </Type>
  </Table>
  <Table Name="dbo.CAP_SV5T" Member="CAP_SV5Ts">
    <Type Name="CAP_SV5T">
      <Column Name="MACAP" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCAP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOLUONGDK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CAP_SV5T_CHITIET_TC" Member="CHITIET_TCs" ThisKey="MACAP" OtherKey="MACAP" Type="CHITIET_TC" />
      <Association Name="CAP_SV5T_PHIEUDK_SV5T" Member="PHIEUDK_SV5Ts" ThisKey="MACAP" OtherKey="MACAP" Type="PHIEUDK_SV5T" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIET_TC" Member="CHITIET_TCs">
    <Type Name="CHITIET_TC">
      <Column Name="MATC" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MACAP" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOIDUNG_TC1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAYCHINHSUA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NOIDUNG_TC2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NOIDUNG_TC3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NOIDUNGTC_4" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="CAP_SV5T_CHITIET_TC" Member="CAP_SV5T" ThisKey="MACAP" OtherKey="MACAP" Type="CAP_SV5T" IsForeignKey="true" />
      <Association Name="TIEUCHI_SV5T_CHITIET_TC" Member="TIEUCHI_SV5T" ThisKey="MATC" OtherKey="MATC" Type="TIEUCHI_SV5T" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHOA" Member="KHOAs">
    <Type Name="KHOA">
      <Column Name="MAKHOA" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKHOA" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SOLUONGSV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KHOA_ACCOUNT" Member="ACCOUNTs" ThisKey="MAKHOA" OtherKey="MAKHOA" Type="ACCOUNT" />
      <Association Name="KHOA_LOP" Member="LOPs" ThisKey="MAKHOA" OtherKey="MAKHOA" Type="LOP" />
    </Type>
  </Table>
  <Table Name="dbo.KQDANHGIA_ACCOUNT" Member="KQDANHGIA_ACCOUNTs">
    <Type Name="KQDANHGIA_ACCOUNT">
      <Column Name="DIEMRL" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DIEMHOCTAP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TEST_THELUC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TN_5NGAYTN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TN_3CHIENDICHLON" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HN_NGOAINGU" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HN_KYNANG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UT_KETNAPDANG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UT_HIENMAU" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UT_BIEUDUONG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNguoiDanhGia" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ACCOUNT_KQDANHGIA_ACCOUNT" Member="ACCOUNT" ThisKey="USERNAME" OtherKey="USERNAME" Type="ACCOUNT" IsForeignKey="true" />
      <Association Name="NGUOIDANHGIA_KQDANHGIA_ACCOUNT" Member="NGUOIDANHGIA" ThisKey="MaNguoiDanhGia" OtherKey="MaNguoiDanhGia" Type="NGUOIDANHGIA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LHTT" Member="LHTTs">
    <Type Name="LHTT">
      <Column Name="STT" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="LOP_LHTT" Member="LOP" ThisKey="MALOP" OtherKey="MALOP" Type="LOP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOP" Member="LOPs">
    <Type Name="LOP">
      <Column Name="MALOP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAKHOA" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONG_SV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LOP_LHTT" Member="LHTTs" ThisKey="MALOP" OtherKey="MALOP" Type="LHTT" />
      <Association Name="KHOA_LOP" Member="KHOA" ThisKey="MAKHOA" OtherKey="MAKHOA" Type="KHOA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDANHGIA" Member="NGUOIDANHGIAs">
    <Type Name="NGUOIDANHGIA">
      <Column Name="MaNguoiDanhGia" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NGUOIDANHGIA_KQDANHGIA_ACCOUNT" Member="KQDANHGIA_ACCOUNTs" ThisKey="MaNguoiDanhGia" OtherKey="MaNguoiDanhGia" Type="KQDANHGIA_ACCOUNT" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUDK_SV5T" Member="PHIEUDK_SV5Ts">
    <Type Name="PHIEUDK_SV5T">
      <Column Name="SOPHIEUDK" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DRL_HK1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DRL_HK2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DRL_TB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KQ_CHATLUONGDOANVIEN" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DD_THANHNIENTTLAMTHEOLOIBAC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DD_HOITHI_TTHCM" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DIEMHK1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DIEMHK2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DIEMTB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HT_BAIVIETKH" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HT_NCKH" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="HT_GIAITHIHOCTHUAT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TEN_THIHOCTHUAT" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TL_SVKHOE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TL_TV_DOITUYENTDTT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DATGIAIHOITHAOCACCAP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TEN_CAPHOITHAO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TN_THAMGIACHIENDICHLON" Type="System.Data.Linq.Binary" DbType="Binary(1)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TN_5HDTN_NAM" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HN_AV_B1" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TEN_AV_KHAC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HN_GIAOLUUQT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HN_GIAICUOCTHI_NNgu" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HN_1KHOAHOCKYNANG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HN_3BUOI_HOITHAOKYNANG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HN_THAMGIA_HDHOINHAP" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UT_KETNAPDANG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UT_HIENMAU" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UT_BIEUDUONG_KHENTHUONG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[KHOKHAN-KIENNGHI]" Member="KHOKHAN_KIENNGHI" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MACAP" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="CAP_SV5T_PHIEUDK_SV5T" Member="CAP_SV5T" ThisKey="MACAP" OtherKey="MACAP" Type="CAP_SV5T" IsForeignKey="true" />
      <Association Name="ACCOUNT_PHIEUDK_SV5T" Member="ACCOUNT" ThisKey="USERNAME" OtherKey="USERNAME" Type="ACCOUNT" IsForeignKey="true" />
    </Type>
  </Table>
</Database>